//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// VoIPClient.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_CALL_VIEW                   101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_VoIPClientTYPE              130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDB_PNG1                        311
#define IDB_PNG2                        312
#define IDB_PNG3                        313
#define IDB_PNG4                        314
#define IDB_PNG5                        315
#define IDB_PNG6                        316
#define IDB_PNG7                        317
#define IDI_MASK                        319
#define IDI_ICON1                       320
#define IDI_HOMER                       320
#define IDD_DLG_ACCOUNT_LOGIN           321
#define IDD_DLG_MANAGE_ACCOUNT          322
#define IDD_DLG_CALL_VIEW               327
#define IDB_BITMAP1                     334
#define IDB_MASK                        334
#define IDD_DLG_CALL_LIST_VIEW          335
#define IDI_LOGIN                       337
#define IDI_SIGNIN                      338
#define IDI_LOGIN_64                    339
#define IDI_ICON4                       340
#define IDI_SIGNIN_64                   340
#define IDD_DLG_START                   343
#define IDB_MOOZ                        345
#define IDB_LOG_IN                      348
#define IDB_RESET_PW                    349
#define IDB_SIGN_IN                     350
#define IDB_LOG_IN_D                    351
#define IDB_RESET_PW_D                  352
#define IDB_SIGN_IN_D                   353
#define IDB_LOG_IN_F                    354
#define IDB_RESET_PW_F                  355
#define IDB_SIGN_IN_F                   356
#define IDD_DLG_SESSION_REGISTER        357
#define IDD_DIALOG2                     358
#define IDD_DLG_CONTACT_REGISTER        358
#define IDD_RESET_PASSWORD              361
#define IDD_DLG_UPDATE_ACCOUNT          366
#define IDD_DIALOG1                     369
#define IDD_DLG_MSGBOX                  369
#define IDB_BMP_CONNECTION              371
#define IDB_BMP_DISCONNECTION           372
#define IDB_ECHO_OFF                    373
#define IDB_ECHO_ON                     374
#define IDB_BMP_VAD_ON                  375
#define IDB_BMP_VAD_OFF                 376
#define IDB_SHUTDOWN                    377
#define IDB_START                       378
#define IDD_CLIENT_VIEW                 379
#define IDR_WAVE1                       383
#define IDR_WAVE2                       385
#define IDB_PNG8                        386
#define IDB_BITMAP2                     393
#define IDB_BMP_DISCONNECT              393
#define ID_VIEW_CALLVIEW                400
#define IDC_ED_EMAIL_ID                 1000
#define IDC_ED_PASSWORD                 1001
#define IDC_IPADDRESS_SERVER            1002
#define IDC_ED_PASSWORD2                1002
#define IDC_ED_ID                       1002
#define IDC_MFCBTN_LOGIN                1004
#define IDC_MFCBTN_SIGN_IN              1005
#define IDC_ED_NAME                     1007
#define IDC_ED_EMAIL                    1007
#define IDC_MFCBTN_CREATE               1008
#define IDC_MFCBTN_UPDATE               1009
#define IDC_MFCBTN_CANCEL               1009
#define IDC_LIST1                       1010
#define IDC_LST_CONTACT_ID              1010
#define IDC_ED_LAST_NAME                1010
#define IDC_ST_LOGO                     1011
#define IDC_ED_PASSWORD_ANSWER          1011
#define IDC_MFCBTN_RESET_PW             1012
#define IDC_BMP_MOOZ                    1013
#define IDC_Client_StartCall            1014
#define IDC_MFCBTN_START                1015
#define IDC_Client_EndCall              1015
#define IDC_COMBO1                      1016
#define IDC_Server_StartCall            1016
#define IDC_COMBO_PASSWORD_QUESTION     1016
#define IDC_Server_EndCall              1017
#define IDC_Server_AddClient            1018
#define IDC_CB_PASSWORD_QUESTION        1019
#define IDC_Server_RemoveClient         1019
#define IDC_ED_SEARCH_NAME              1020
#define IDC_Client_EncAlgo              1020
#define IDC_MFCBTN_SEARCH               1021
#define IDC_Client_EncKey               1021
#define IDC_LIST3                       1022
#define IDC_Client_AudioCodec           1022
#define IDC_LT_CONTACT                  1022
#define IDC_LIST4                       1023
#define IDC_Client_VideoCodec           1023
#define IDC_LT_PARTICIPANTS             1023
#define IDC_DP_DATE                     1024
#define IDC_Client_ClientIP             1024
#define IDC_MFCBTN_RIGHT                1025
#define IDC_Client_ServerIP             1025
#define IDC_MFCBTN_LEFT                 1026
#define IDC_LIST2                       1026
#define IDC_LT_CONTACT_NAMES            1026
#define IDC_Server_EncAlgo              1026
#define IDC_DP_TIME_START               1027
#define IDC_Server_EncKey               1027
#define IDC_DP_TIME_END                 1028
#define IDC_Server_AudioCodec           1028
#define IDC_Server_VideoCodec           1029
#define IDC_Server_MaxClient            1030
#define IDC_Server_ServerIP             1031
#define IDC_Server_RIDForStart          1032
#define IDC_Server_RIDForAdd            1033
#define IDC_Server_ClientIP             1034
#define IDC_Server_CID                  1035
#define IDC_SET_HANDLER                 1036
#define IDC_DISPLAY                     1037
#define IDC_ED_ACCOUNT_ID               1038
#define ID_MFCBTN_RESET                 1039
#define IDC_MFCBTN_UPDATE_CONTACT       1040
#define IDC_ST_MSG                      1041
#define IDC_MFCBTN_SHUTDOWN             1042
#define IDC_CUSTOM1                     1043
#define IDC_MFCBTN_CONNECT              1044
#define IDC_MFC_VAD                     1045
#define IDC_MFCBUTTON3                  1046
#define IDC_MFC_ECHO                    1046
#define IDC_IMAGE_VIEW                  1047
#define IDC_SPIN_PRESET                 1049
#define ID_TEST_32771                   32771
#define ID_TEST_32772                   32772
#define ID_TEST_LOG_IN                  32773
#define ID_TEST_LOG_OUT                 32774
#define ID_TEST_32775                   32775
#define ID_TEST_32776                   32776
#define ID_TEST_CREATE_USER             32777
#define ID_TEST_UPDATE_USER             32778
#define ID_SETTING_32779                32779
#define ID_SETTING_TEST                 32780
#define ID_DELETE_USER                  32781
#define ID_JOIN_SESSION                 32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        383
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
