// VoIPClient.idl: VoIPClient.exe의 형식 라이브러리 소스

// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(VoIPClient.tlb)입니다.

[ uuid(a7e61e7c-8d36-4166-806e-49110175b267), version(1.0) ]
library VoIPClient
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CVoIPClientDoc의 기본 디스패치 인터페이스

	[ uuid(f65ec69c-f4a0-4017-88b1-31f86d5968b1) ]
	dispinterface IVoIPClient
	{
		properties:

		methods:
	};

	//  CVoIPClientDoc에 대한 클래스 정보

	[ uuid(7f4b2f2c-80e8-4046-a282-d5fb198ab3cf) ]
	coclass CVoIPClientDoc
	{
		[default] dispinterface IVoIPClient;
	};
};
