// VoIPClient.idl: VoIPClient.exe의 형식 라이브러리 소스

// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(VoIPClient.tlb)입니다.

[ uuid(88b9a738-8451-4366-92b0-cd60e6f8960f), version(1.0) ]
library VoIPClient
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CVoIPClientDoc의 기본 디스패치 인터페이스

	[ uuid(ada92bd1-55f0-4922-950a-052e440958fb) ]
	dispinterface IVoIPClient
	{
		properties:

		methods:
	};

	//  CVoIPClientDoc에 대한 클래스 정보

	[ uuid(29efbe4f-bbc7-49a2-9a8c-8a6ec6295c7f) ]
	coclass CVoIPClientDoc
	{
		[default] dispinterface IVoIPClient;
	};
};
